services:
  ipbcb_server:
    container_name: ipbcb-server
    build:
      context: .
    image: ipbcb-server:dev
    env_file:
      - ./.env
    ports:
      - 8002:8000
    volumes:
      - ./server:/server
      - ./server/static/:/server/static/
      - ./server/media:/server/media/
